module.exports = {
  S1: [
    "S1",
    {
      type: "category",
      label: "中一上",
      link: { type: "generated-index", title: "中一級上學期課文" },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "單元二：敘事寫人",
          link: {
            type: "generated-index",
            slug: "/category/S1/單元二：敘事寫人",
          },
          collapsed: false,
          items: ["S1/單元二：敘事寫人/2.5岳飛之少年時代"],
        },
        {
          type: "category",
          label: "單元四：詩歌欣賞",
          link: {
            type: "generated-index",
            slug: "/category/S1/單元四：詩歌欣賞",
          },
          collapsed: false,
          items: [
            "S1/單元四：詩歌欣賞/4.5燕詩",
            "S1/單元四：詩歌欣賞/4.26涉江采芙蓉"
          ],
        },
      ],
    },
  ],
  S2: [
    "S2",
    {
      type: "autogenerated",
      dirName: "S2",
    },
  ],
  S3: [
    "S3",
    {
      type: "category",
      label: "中三上",
      link: { type: "generated-index", title: "中三級上學期課文" },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "單元一：說明的語言",
          link: {
            type: "generated-index",
            slug: "/category/S3/單元一：說明的語言",
          },
          collapsed: false,
          items: ["S3/單元一：說明的語言/1.5核工記"],
        },
        {
          type: "category",
          label: "單元二：記敘的方法和詳略",
          link: {
            type: "generated-index",
            slug: "/category/S3/單元二：記敘的方法和詳略",
          },
          collapsed: false,
          items: [
            "S3/單元二：記敘的方法和詳略/2.5爸爸的花兒落了",
            "S3/單元二：記敘的方法和詳略/2.24閒情記趣（節錄）",
          ],
        },
        {
          type: "category",
          label: "單元四：詞曲欣賞",
          link: {
            type: "generated-index",
            slug: "/category/S3/單元四：詞曲欣賞",
          },
          collapsed: false,
          items: [
            "S3/單元四：詞曲欣賞/4.6水調歌頭．明月幾時有",
            "S3/單元四：詞曲欣賞/4.18虞美人．春花秋月何時了",
          ],
        },
      ],
    },
  ],
};
