module.exports = {
  S1: [
    "S1/index",
    {
      type: "category",
      label: "單元二：敘事寫人",
      link: { type: "doc", id: "S1/單元二：敘事寫人/index", },
      items: [
        "S1/單元二：敘事寫人/2.5岳飛之少年時代",
      ],
    },
    {
      type: "category",
      label: "單元三：借事抒情",
      link: { type: "doc", id: "S1/單元三：借事抒情/index", },
      items: [
        "S1/單元三：借事抒情/3.5背影",
      ],
    },
    {
      type: "category",
      label: "單元四：詩歌欣賞",
      link: { type: "doc", id: "S1/單元四：詩歌欣賞/index", },
      items: [
        "S1/單元四：詩歌欣賞/4.5燕詩",
        "S1/單元四：詩歌欣賞/4.12客至",
        "S1/單元四：詩歌欣賞/4.26涉江采芙蓉",
        "S1/單元四：詩歌欣賞/4.30從軍行七首（其二）",
        "S1/單元四：詩歌欣賞/4.34送友人",
      ],
    },
    {
      type: "category",
      label: "單元六：景物描寫（一）",
      link: { type: "doc", id: "S1/單元六：景物描寫（一）/index", },
      items: [
        'S1/單元六：景物描寫（一）/6.5風雪中的北平',
        'S1/單元六：景物描寫（一）/6.23海濱仲夏夜',
        'S1/單元六：景物描寫（一）/6.29海上的日出',
      ],
    },
    {
      type: "category",
      label: "單元七：說明的方法和順序",
      link: { type: "doc", id: "S1/單元七：說明的方法和順序/index", },
      items: [
        'S1/單元七：說明的方法和順序/生物之間的微妙關係',
      ],
    },
    {
      type: "category",
      label: "單元八：借事說理",
      link: { type: "doc", id: "S1/單元八：借事說理/index", },
      items: [
        'S1/單元八：借事說理/曾子殺豬',
        'S1/單元八：借事說理/賣油翁',
      ],
    },
  ],

  S2: [
    "S2/index",
    // { type: "autogenerated", dirName: "S2", },
  ],

  S3: [
    "S3/index",
    {
      type: "category",
      label: "單元一：說明的語言",
      link: { type: "doc", id: "S3/單元一：說明的語言/index", },
      items: [
        'S3/單元一：說明的語言/1.5核工記',
      ],
    },
    {
      type: "category",
      label: "單元二：記敘的方法和詳略",
      link: { type: "doc", id: "S3/單元二：記敘的方法和詳略/index", },
      items: [
        'S3/單元二：記敘的方法和詳略/2.5爸爸的花兒落了',
        'S3/單元二：記敘的方法和詳略/2.24閒情記趣（節錄）',
      ],
    },
    {
      type: "category",
      label: "單元四：詞曲欣賞",
      link: { type: "doc", id: "S3/單元四：詞曲欣賞/index", },
      items: [
        'S3/單元四：詞曲欣賞/4.6水調歌頭．明月幾時有',
        'S3/單元四：詞曲欣賞/4.13天淨沙．秋思',
        'S3/單元四：詞曲欣賞/4.18虞美人．春花秋月何時了',
      ],
    },
    {
      type: "category",
      label: "單元六：小說與戲劇欣賞",
      link: { type: "doc", id: "S3/單元六：小說與戲劇欣賞/index", },
      items: [
        'S3/單元六：小說與戲劇欣賞/6.5孔明借箭',
        'S3/單元六：小說與戲劇欣賞/一碗陽春麵',
      ],
    },
    {
      type: "category",
      label: "單元七：論證的方法",
      link: { type: "doc", id: "S3/單元七：論證的方法/index", },
      items: [
        'S3/單元七：論證的方法/最苦與最樂',
      ],
    },
    {
      type: "category",
      label: "單元九：文言選讀（三）",
      link: { type: "doc", id: "S3/單元九：文言選讀（三）/index", },
      items: [
        'S3/單元九：文言選讀（三）/論語八則',
        'S3/單元九：文言選讀（三）/論四端',
      ],
    },
    {
      type: "category",
      label: "作品選讀",
      link: { type: 'generated-index', slug: '/S3/作品選讀', },
      items: [{ type: 'autogenerated', dirName: 'S3/作品選讀', },],
    },
  ],

  settext: [
    {
      type: 'category',
      label: '指定文言經典學習材料',
      link: { type: 'generated-index', slug: '/settext', },
      items: [{ type: 'autogenerated', dirName: 'settext', },],
    },
  ],
};
