import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import S1 from "./docs/contents/S1/PassageList.json";
import S2 from "./docs/contents/S2/PassageList.json";
import S3 from "./docs/contents/S3/PassageList.json";

const sidebar: SidebarsConfig = {
  S1,
  S2,
  S3,
  
  settext: [
    {
      type: "category",
      label: "指定文言經典學習材料",
      link: { type: "generated-index", slug: "/settext" },
      items: [{ type: "autogenerated", dirName: "settext" }],
    },
  ],

  dse: [
    {
      type: "category",
      label: "歷屆文憑試閱讀篇章",
      link: { type: "generated-index", slug: "/dse" },
      items: [{ type: "autogenerated", dirName: "dse" }],
    },
  ],
};

export default sidebar;
