module.exports = {
  S1: [
    'S1',
    {
      type: 'category',
      label: '中一上',
      link: { type: 'generated-index', title: '中一上學期課文', },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '單元二：敘事寫人',
          link: { type: 'generated-index', slug: '/category/S1/單元二：敘事寫人', },
          collapsed: false,
          items: [
            'S1/單元二：敘事寫人/2.5岳飛之少年時代',
          ],
        },
      ]
    },
  ],
  S2: [
    'S2',
    {
      type: 'autogenerated',
      dirName: 'S2',
    },
  ],
  S3: [
    'S3',
    {
      type: 'category',
      label: '中三上',
      link: { type: 'generated-index', title: '中三上學期課文', },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '單元一：說明的語言',
          link: { type: 'generated-index', slug: '/category/S3/單元一：說明的語言', },
          collapsed: false,
          items: [
            'S3/單元一：說明的語言/1.5核工記',
          ],
        },
        {
          type: 'category',
          label: '單元四：詞曲欣賞',
          link: { type: 'generated-index', slug: '/category/S3/單元四：詞曲欣賞', },
          collapsed: false,
          items: [
            'S3/單元四：詞曲欣賞/4.6水調歌頭．明月幾時有',
          ],
        },
      ]
    },
  ],
};